"""
Django settings for CMPBackend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Asegúrate de que esta línea esté al principio si no lo está

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&jlcy0on-yi!apy-5m6)6-rpvy@)%2k-1%(bumxfsjep)ei**n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',                     # Para manejar CORS con el frontend de React
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tus aplicaciones de terceros
    'rest_framework',                  # Django REST Framework
    'rest_framework_simplejwt',        # Para autenticación JWT
    # Tus aplicaciones del proyecto
    'task_api',
    'users',
    'cryptotools',
    'cryptolearn',
    'blogmine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CRÍTICO: Debe ir ANTES de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CryptoMineProBackend.urls' # Asegúrate que este sea el nombre de tu proyecto interno

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CryptoMineProBackend.wsgi.application' # Asegúrate que este sea el nombre de tu proyecto interno


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- INICIO DE NUEVAS CONFIGURACIONES DE DRF y CORS ---
# Configuración de Django REST Framework (DRF)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication', # Usaremos JWT para autenticación
        'rest_framework.authentication.SessionAuthentication',        # Para el panel de administración
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly', # Por defecto, requiere autenticación para escribir, permite lectura pública
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10 # Define el tamaño de página para paginación por defecto
}

# Configuración de CORS (Cross-Origin Resource Sharing)
# Ya tenías CORS_ALLOWED_ORIGINS, así que lo mantendremos.
# Si prefieres permitir *todos* los orígenes durante el desarrollo para simplificar,
# puedes usar CORS_ALLOW_ALL_ORIGINS = True en lugar de CORS_ALLOWED_ORIGINS,
# pero no ambas al mismo tiempo.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # La URL de tu servidor de desarrollo React/Vite
    "http://127.0.0.1:5173", # A veces localhost se resuelve a 127.0.0.1
    # Si tienes más frontends o si tu frontend se despliega en otro dominio, añádelos aquí.
]
# --- FIN DE NUEVAS CONFIGURACIONES DE DRF y CORS ---

# Configuración del modelo de usuario personalizado
# Esto le dice a Django que use tu modelo CustomUser de la aplicación 'users'
AUTH_USER_MODEL = 'users.CustomUser'
